### ISSUE TITLE
use argparse library for command line argument parsing

### ISSUE THREAD

**Issue by mgerhold** [mgerhold/oopetris#43]

**Comment by Totto16** [comment]
Is this necessary, since for the future it's better to have buttons and file pickers for the user, so this would only be temporary? :thinking:

**Comment by mgerhold** [comment]
I guess that we will always need some command line argument parsing (if only for testing purposes), so I'd like to make this a permanent thing. We already have the replay feature and I think network related tests will also need some argument parsing later.

**Comment by Totto16** [comment]
yes they do, and you're rigth, (see e.g [here](https://github.com/mgerhold/oopetris/blob/fe3048ba323660e9597ce65c55e94a62fbb4d287/src/main.cpp))but I would prefer  the library `argparse` [here](https://github.com/p-ranav/argparse) since it's a simple yet powerfull parser both available on vcpkg and meson :sweat:  or is TCLAP that much better?

**Comment by mgerhold** [comment]
If it's easier, let's use argparse instead 👍
